# Generated by Django 4.1.1 on 2022-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Shooting', 'Shooting'), ('Finishing', 'Finishing'), ('Dribbling', 'Dribbling'), ('Athleticism', 'Athleticism'), ('Injuries', 'Injuries')], default='Shooting', max_length=25),
        ),
    ]
