# Generated by Django 4.1.1 on 2022-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Shooting', 'Shooting'), ('Finishing', 'Finishing'), ('Dribbling', 'Dribbling'), ('Athleticism', 'Athleticism'), ('Injuries', 'Injuries'), ('Defence', 'Defence'), ('TeamPlay', 'TeamPlay')], default='Shooting', max_length=25),
        ),
    ]
