# Generated by Django 4.1.1 on 2022-09-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
