# Generated by Django 4.1.1 on 2022-09-21 18:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_content_comment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
